name: Build .pyi
run-name: ${{ github.actor }} is building a new .pyi file
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run generator
      run: |
        python -m ./generate_resolve_type_hints.py
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: pyi
        path: ./output/DaVinciResolveScript.pyi